### ISSUE TITLE
V2.0.1 missing comment terminator

### ISSUE THREAD

**Issue by lceric** [Crystal-Spider/jsdoc-generator#20]
**Describe the bug**
V2.0.1 missing comment terminator

**To Reproduce**
1. Writing method
```js
const run = (a) => {
  console.log(a);
}
```
2. run `jsDoc generate`

**Expected behavior**
Like v1.3.0, correct code comments

**Screenshots**
v1.3.0
<img width="621" alt="image" src="https://github.com/Crystal-Spider/jsdoc-generator/assets/25276032/f4299f8d-2ba8-4271-a9ef-59da26486a6f">
v2.0.1
<img width="535" alt="image" src="https://github.com/Crystal-Spider/jsdoc-generator/assets/25276032/676a3109-1483-48fd-be5a-d3d5bfb40eb0">
**Additional context**

**Environment used**
Typescript version: 5.3.3
VSC versione: 1.86.2
OS: Mac Darwin x64 23.2.0

**Comment by Crystal-Spider** [comment]
Thanks for reporting, I'll look into it!

**Comment by Crystal-Spider** [comment]
This is fixed in v2.0.2, thanks again!
