### ISSUE TITLE
Date locale options

### ISSUE THREAD

**Issue by CurtR95** [Crystal-Spider/jsdoc-generator#22]
**Is your feature request related to a problem? Please describe.**
When generating a new JSDoc with jsdoc-generator.includeDate enabled it uses American date format "mm/dd/yyyy", however, I code in both Japanese and British codebases, which use either "yyyy/mm/dd" or "dd/mm/yyyy", which requires a minor change on each generation.

**Describe the solution you'd like**
Ability to set the locale of the date format in the settings. I.e. a string in preferences which lists "mm/dd/yyyy"

**Describe alternatives you've considered**
I have considered editing the snippet directly or looking at basic snippets, but I miss features of this generator too much

**Environment used**

VSC version: 1.88.1
OS: Windows 10

**Comment by Crystal-Spider** [comment]
Currently, the date format is based on your locale (I use `toLocaleDateString`).  
Sure enough, I can change that. I'll soon release a new version.

**Comment by Crystal-Spider** [comment]
Implemented in v2.1.0
