### ISSUE TITLE
Wrong return when there is type predicate

### ISSUE THREAD

**Issue by chouchouji** [Crystal-Spider/jsdoc-generator#28]
# Describe the bug

Wrong return when there is type predicate

# To Reproduce

```ts
export function isNotEmptyArray(value: unknown): value is Array<any> {
  return Array.isArray(value) && value.length > 0;
}
```

# Expected behavior
I am not sure that how to fix it. If you have some good ideas, please share them. 

# Screenshots

![image](https://github.com/user-attachments/assets/6203948f-1e30-4f62-9ee7-92fc0e618639)

**Additional context**

**Environment used**
Typescript version: x.x.x
VSC versione: x.x.x

**Comment by Crystal-Spider** [comment]
Hi! I think that's the most proper way to document the type, since it's exactly the type you specify and that is returned when I ask the TypeScript compiler for the function return type.

**Comment by Crystal-Spider** [comment]
If you have a suggestion on a change for this specific return type, let me know.

**Comment by chouchouji** [comment]
Thanks for your reply! I think it is not the return type of function. It specifies the type of parameter val.

**Comment by Crystal-Spider** [comment]
Yeah, I know. But look at your TypeScript return type definition:
`): val is Array<any>`
So already in code you define the return type including the parameter name, however it's not a definition of the parameter's type, but rather of the function return type.

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/e616a2a6-1b10-4f3b-a0f1-51e68ada84d6)

I think it is a little weird. the return type of this function should be `boolean`, but the docs not.....

**Comment by Crystal-Spider** [comment]
In TypeScript, type narrowing predicates and "classic" predicates are quite different.  
A function returning a predicate allows for the compiler to narrow down the type of the input variable to the type specified in the predicate type definition. This is unlike a function returning a boolean, which does not allow for type narrowing at all.

![image](https://github.com/user-attachments/assets/f1a9630d-e15c-4c50-a9cf-6f984c3a8f7f)
Take a look at what the intellisense shows for each function:
![Untitled-1](https://github.com/user-attachments/assets/c590872b-28d2-4c3a-974d-078861aa6024)

So, to me, it seems correct that the return type is *not* boolean, but is the predicate type instead.

**Comment by chouchouji** [comment]
Thanks for your reply again! I get it.
